/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InboxImportRouteImport } from './routes/inbox-import'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as ApplicationsIdRouteImport } from './routes/applications/$id'
import { Route as OauthGoogle_mailReturnRouteImport } from './routes/oauth/google_mail/return'
import { Route as OauthMicrosoft_outlookReturnRouteImport } from './routes/oauth/microsoft_outlook/return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxImportRoute = InboxImportRouteImport.update({
  id: '/inbox-import',
  path: '/inbox-import',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdRoute = ApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogle_mailReturnRoute = OauthGoogle_mailReturnRouteImport.update({
  id: '/oauth/google_mail/return',
  path: '/oauth/google_mail/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthMicrosoft_outlookReturnRoute =
  OauthMicrosoft_outlookReturnRouteImport.update({
    id: '/oauth/microsoft_outlook/return',
    path: '/oauth/microsoft_outlook/return',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/inbox-import': typeof InboxImportRoute
  '/interviews': typeof InterviewsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/oauth/google_mail/return': typeof OauthGoogle_mailReturnRoute
  '/oauth/microsoft_outlook/return': typeof OauthMicrosoft_outlookReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/inbox-import': typeof InboxImportRoute
  '/interviews': typeof InterviewsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/applications': typeof ApplicationsIndexRoute
  '/oauth/google_mail/return': typeof OauthGoogle_mailReturnRoute
  '/oauth/microsoft_outlook/return': typeof OauthMicrosoft_outlookReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/inbox-import': typeof InboxImportRoute
  '/interviews': typeof InterviewsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/oauth/google_mail/return': typeof OauthGoogle_mailReturnRoute
  '/oauth/microsoft_outlook/return': typeof OauthMicrosoft_outlookReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/analytics'
    | '/auth'
    | '/inbox-import'
    | '/interviews'
    | '/settings'
    | '/sitemap.xml'
    | '/applications/$id'
    | '/applications/'
    | '/oauth/google_mail/return'
    | '/oauth/microsoft_outlook/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/analytics'
    | '/auth'
    | '/inbox-import'
    | '/interviews'
    | '/settings'
    | '/sitemap.xml'
    | '/applications/$id'
    | '/applications'
    | '/oauth/google_mail/return'
    | '/oauth/microsoft_outlook/return'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/analytics'
    | '/auth'
    | '/inbox-import'
    | '/interviews'
    | '/settings'
    | '/sitemap.xml'
    | '/applications/$id'
    | '/applications/'
    | '/oauth/google_mail/return'
    | '/oauth/microsoft_outlook/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  InboxImportRoute: typeof InboxImportRoute
  InterviewsRoute: typeof InterviewsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApplicationsIdRoute: typeof ApplicationsIdRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  OauthGoogle_mailReturnRoute: typeof OauthGoogle_mailReturnRoute
  OauthMicrosoft_outlookReturnRoute: typeof OauthMicrosoft_outlookReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox-import': {
      id: '/inbox-import'
      path: '/inbox-import'
      fullPath: '/inbox-import'
      preLoaderRoute: typeof InboxImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$id': {
      id: '/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof ApplicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google_mail/return': {
      id: '/oauth/google_mail/return'
      path: '/oauth/google_mail/return'
      fullPath: '/oauth/google_mail/return'
      preLoaderRoute: typeof OauthGoogle_mailReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/microsoft_outlook/return': {
      id: '/oauth/microsoft_outlook/return'
      path: '/oauth/microsoft_outlook/return'
      fullPath: '/oauth/microsoft_outlook/return'
      preLoaderRoute: typeof OauthMicrosoft_outlookReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  InboxImportRoute: InboxImportRoute,
  InterviewsRoute: InterviewsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApplicationsIdRoute: ApplicationsIdRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  OauthGoogle_mailReturnRoute: OauthGoogle_mailReturnRoute,
  OauthMicrosoft_outlookReturnRoute: OauthMicrosoft_outlookReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
